Ruby group capstone - Catalog of my things
AbuTalha3/catalog-of-my-things pull request #43
Opened 2023-11-22 15:07 UTC by AbuTalha3

**In this PR we (@siddghosh108 , @jkanyi-web , @AbuTalha3 ) have**

- Implemented Each class from the [UML class diagram](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/images/catalog_of_my_things.png) and  created them in a separate .rb file.
- All associations (1-to-many relationships) and aggregations (parent-child relationships) between classes are implemented.
- All properties visible in the diagram have been defined and set up in the constructor method. Exception: properties for the 1-to-many relationships should NOT be set in the constructor method. Instead, they should have a custom setter method created.
- All methods visible in the diagram have been implemented:
add_item method (in all classes that have that method)
- It takes an instance of the Item class as an input.
- It adds the input item to the collection of items.
- It  adds self as a property of the item object (by using the correct setter from the item object).
-can_be_archived?() in the Item class
- It returns true if published_date is older than 10 years.
otherwise, it returns false.
- move_to_archive() in the Item class
- It reuses can_be_archived?() method.
- It changes the archived property to true if the result of the can_be_archived?() method is true.
- It does nothing if the result of the can_be_archived?() method is false.
-can_be_archived?() in the Book class
- It overrides the method from the parent class.
- It returns true if parent's method returns true OR if cover_state equals to "bad".
otherwise, it  returns false.
-can_be_archived?() in the MusicAlbum class
- It overrides the method from the parent class.
- It returns true if parent's method returns true AND if on_spotify equals true.
otherwise, it  returns false.
- can_be_archived?() in the Movie class
- It overrides the method from the parent class.
- It returns true if parent's method returns true OR if silent equals true.
otherwise, it  returns false.
- can_be_archived?() in the Game class
- It overrides the method from the parent class.
- It returns true if parent's method returns true AND if last_played_at is older than 2 years.
otherwise, it  returns false.
Added unit tests for all implemented methods.
User interface
Created a main.rb file that  serves as your console app entry-point.
The console app, at the start:
Presents the user with a list of options to perform.
Lets users choose an option.
If needed, can be asked for parameters for the option.
Have a way to quit the app.
The following options are available:
List all books
List all music albums
List all movies
List of games
List all genres (e.g 'Comedy', 'Thriller')
List all labels (e.g. 'Gift', 'New')
List all authors (e.g. 'Stephen King')
List all sources (e.g. 'From a friend', 'Online shop')
Adds a book
Adds a music album
Adds a movie
Adds a game
All data can be preserved by saving collections in .json files.
Database
- Created a schema.sql file with tables that will be analogical to the structure of the classes in your app. As you cannot implement inheritance in the database tables - added all properties and associations from the parent Item class as table columns to all tables based on the child classes.  It can be used to store data in the future.

2023-11-22 16:27 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @AbuTalha3, @siddghosh108, and @jkanyi-web
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All options are working :heavy_check_mark: 
- Most of the associations are correct :heavy_check_mark: 
- Added schema file with correct data :100: :heavy_check_mark: 
- All tests are passing :heavy_check_mark: 
- Preserved data in json files :heavy_check_mark: 
- Good PR description :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-22 16:27 UTC, tresorsawasawa commented on README.md
> +
- [ ] Good job trying to record the video presenting your application. However as it is required for the project, kindly ensure that you video has the **maximum length of the video is 5 minutes** and **all the members appear in the video and talk about the project**. Make sure you record another one that includes all the below features:
  *  The student recorded a video presenting the features of the project.
  * The maximum length of the video is 5 minutes.
  * The video contains a clear and objective description of the project in professional English. The topic and purpose of the project are made clear.
  * All the members in the video should appear in the video and talk about the project.
  * The video contains a highlight about a piece of the code the student finds interesting or is proud of making.

2023-11-22 16:27 UTC, tresorsawasawa commented on classes/games-and-authors/games.rb
> +
- [ ] As required for the project and according the [UML class diagram](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/images/catalog_of_my_things.png), kindly ensure that `Game` class inherits from the `Item` class for good parent-child relationships implementation

2023-11-22 16:27 UTC, tresorsawasawa commented on classes/item.rb
> +  end
- [ ] As required for the project to correctly setup the associations (1-to-many relationships) between classes, kindly ensure that you update the `Item` class as it should have one `Genre`, `Author` and `Label`. For this you need to implement the related method to each one. Below is an example(`# genre` method) that you can refer to implement others:
```ruby
class Item
    attr_reader :genre, :author, :label
    ...

    def genre=(genre)
      @genre = genre
      genre.items.push(self) unless genre.items.include?(self)
    end

    def author=(author)
      ...
    end

    def label=(label)
    ....
    end
    
    end

    ...
  end
```

2023-11-22 16:27 UTC, tresorsawasawa commented on classes/item.rb
> +
- [ ] According to the the the [UML class diagram](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/images/catalog_of_my_things.png), kindly ensure that the `# can_be_archived?` method is set up as `private` method. I noticed that you didn't use this approach in all your classes, so I recommend to update them by applying it. 
**All methods starting with `-` have to be `private`** and the ones starting with `+` have to be `public`. For example:
```ruby
  class  Item
  attr_reader :genre, :author, :label
  .
  .
  .
  # public method
  def move_to_archive
    ...
  end

   # all methods above the 'private' key word are public

  private

   # all methods below the 'private' key word are private
   def can_be_archived?
    ...
   end
 end
```

2023-11-22 16:27 UTC, tresorsawasawa commented on app.rb
> +    puts 'Please enter the covers state:'
- [ **OPTIONAL** ] For UI reasons, I think it would be better if you add some example of data to be added while completing/using your application. This will help users enter correct data. For example, for `date` you can add format dat example(`DD/MM/YYYY`), for `cover state` you can add the example such as(`good` or `bad`),... I suggest you apply this to all inputs(if needed)
```ruby
 # example
 def add_book(app)
    ...
     puts 'Please enter the covers state(good/bad):'
   ...
```

2023-11-22 18:39 UTC, siddghosh108 commented on classes/item.rb
> +
According to your suggestion made changes in the following files inside classes folder:
1.book.rb
2.item.rb
3.music_album.rb
4.games.rb

and the code changed was:

private
  
  def can_be_archived?
    (Time.now - @last_played_at) >= 2 * 365 * 24 * 60 * 60
  end

2023-11-22 18:45 UTC, siddghosh108 commented on classes/item.rb
> +  end
As per your suggestions created the following methods inside the item class:

def genre=(genre)
    @genre = genre
    genre.items.push(self) unless genre.items.include?(self)
  end

  def author=(author)
    @author = author
    author.items.push(self) unless author.items.include?(self)
  end

  def label=(label)
    @label = label
    label.items.push(self) unless label.items.include?(self)
  end

2023-11-22 19:00 UTC, siddghosh108 commented on classes/games-and-authors/games.rb
> +
As per your suggestion now the Game class inherits from item class:

class Game < Item
  attr_accessor :multiplayer, :last_played_at

  def initialize(multiplayer, last_played_at)
    @multiplayer = multiplayer
    @last_played_at = last_played_at
  end

  private

  def can_be_archived?
    (Time.now - @last_played_at) >= 2 * 365 * 24 * 60 * 60
  end
end

2023-11-24 01:49 UTC, AbuTalha3 commented on README.md
> +
Added Video while three of us (partners) are on a zoom call, presenting our code for 5 minutes.

2023-11-24 02:40 UTC, zieeco requested changes
Hi @Team,

<img height="80" src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>



Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- App's UI has the functionality ✔️
- Implemented most of the requested changes ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._




## Optional suggestions

- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-24 02:40 UTC, zieeco commented on classes/item.rb
> +  end
- Hey Team, as this is a requirement for this project and as requested by the previous reviewer, let's try to resolve this issue raised on the associations.

2023-11-24 04:05 UTC, franclobo approved these changes
Hi team,

# STATUS: APPROVED 😃  

![git-merge](https://github.com/AbuTalha3/catalog-of-my-things/assets/58642949/3f108214-4a95-436c-8ff3-185a32f0a1a8)

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

## Highlights

- No linter errors ✔️
- Descriptive PR ✔️
- Correct Github flow ✔️ 

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-11-24 04:13 UTC, merged